---
title: "Mapping Ratification of UN Convention on Racial Discrimination"
author: "Carlos Yordan"
date: "5/20/2022"
output: html_document
---
#1. LOAD LIBRARIES

```{r setup, include=FALSE}

library(tidyverse)
library(maps)
library(ggmap)
library(countrycode)
library(RColorBrewer)
library (ggthemes)
library (sf)


knitr::opts_chunk$set(echo = TRUE)
```

#2. LOAD RAW DATA FROM GitHub

```{r}

## changes were done in the GitHub repository

hr <- read.csv ("https://raw.githubusercontent.com/world-politics-datalab/humanrights-treaty-racial_discrimination/main/anti_racial_discrimination_1966.csv")

#fix Namibia's iso2 which reads as "NA" rather than NA

hr$iso2 <- countrycode (hr$member, origin= "country.name", destination = "iso2c", )

```

#3. LET'S CREATE A DF WITH MAPPING DATA FOR THE WORLD

```{r}

wmap <- map_data ("world")

# check the map

worldplot <- ggplot()+
  geom_polygon(data=wmap, aes(x=long, y=lat, group = group))+
  coord_fixed(1.3)

worldplot
  
```

#4. LET's COMBINE THE TWO DATASETS

```{r}
#let's add iso2

wmap$iso2 <- countrycode (wmap$region, origin= "country.name", destination = "iso2c", )

#join the map with the hr data

wmap_hr <- wmap %>%
  left_join (hr, by = c("iso2" = "iso2"))

## filter NAs

wmap_hr <- filter(wmap_hr, !is.na(status))

```

#5. MAKE THE MAP WITH THE "STATE.PARTY" VARIABLE:

```{r}
## changes were done in the GitHub file - change fill from "state.party" to "status" to see what happens.

ggplot(wmap_hr, aes(long, lat, group = group)) +
  coord_fixed(1.3)+
  geom_polygon(aes(fill = state.party),
               colour = alpha("grey", 1/2), size = 0.05)  +
  geom_polygon(data =wmap_hr, colour = "white", fill = NA) +
  ggtitle("Ratification of the 1966 International Convention on the Elimination of All Forms of Racial Discrimination") +
  scale_fill_distiller(palette = "RdBu", direction= 1)+
  theme_minimal()
```

#6. MAP USING THE "STATUS" VARIABLE

```{r}

ggplot(wmap_hr, aes(long, lat, group = group)) +
  coord_fixed(1.3)+
  geom_polygon(aes(fill = status))+
  geom_polygon(data =wmap_hr, colour = "white", fill = NA) +
  ggtitle("Ratification of the 1966 International Convention on the Elimination of All Forms of Racial Discrimination") +
  scale_y_continuous()+
  theme_minimal()


```

